### 해당 게시판 좋아요
POST http://localhost:8080/board/1/list/1/detailview/likes
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2ODU5NjgwODcsImV4cCI6MTY4NTk2OTg4NywiaWQiOjEsInN1YiI6ImFmYUBiYmIuY29tIn0.5Sr-HSob4Bbhz0BxTt5S03M0KXbP82dHuKm7eWH9vrM


### 해당 게시판 좋아요 취소
DELETE http://localhost:8080/board/1/list/1/detailview/likes
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2ODU5NjgwODcsImV4cCI6MTY4NTk2OTg4NywiaWQiOjEsInN1YiI6ImFmYUBiYmIuY29tIn0.5Sr-HSob4Bbhz0BxTt5S03M0KXbP82dHuKm7eWH9vrM