spring:
  datasource:
    url: jdbc:mysql://localhost:3306/communityDB
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  redis:
    host: localhost
    port: 6379

logging:
  level:
    org.hibernate.sql: trace
    org.hibernate.type: trace

jwt:
  secretkey: ProjectOfCommunityBoard